version: ~> 1.0
os: linux
dist: focal
language: node_js
 node_js:
  - "14"
android:
  components:
    - tools
    - platform-tools
    - android-13
env:
  TWRP_DEVICE: X70
  TWRP_VERSION: 5.1

group: previous
git:
  depth: 1

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update:
      - true

services:
  - docker

before_install:
  - echo "Setting up environment..."
  - export TWRP_SOURCE=$(pwd)
  - export ANDROID_COMPILE_WITH_JACK=1
  - export CCACHE_EXEC=/usr/local/bin/ccache
  - docker pull fr3akyphantom/droid-builder:focal



before_script:
  - cd $HOME && mkdir twrp
  - TWRP_SOURCE="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-5.1-norepo-20200222.tar.xz"
  # Use below line If Building for Marshmallow-based Devices
  - wget -q ${TWRP_SOURCE} -O $HOME/twrp.tar.xz
  - tar -xJf $HOME/twrp.tar.xz --directory $HOME/twrp/ && rm $HOME/twrp.tar.xz

script:
  - echo "Starting build..."
  - travis_wait 30 make -j$(nproc --all) recoveryimage
  - travis_wait 30 docker run -e CI=true nikitorex/prebuilt npm run test -- --coverage
  # No changes here
  - cd $HOME/twrp/
  - cd $HOME/twrp/ && git clone https://github.com/NikitoRex/prebuilt.git device/Cubot/X70
  - rm -rf bootable/recovery && git clone https://github.com/NikitoRex/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/builder/twrp/:rw,z" -v "${HOME}/.ccache:/srv/ccache:rw,z" fr3akyphantom/droid-builder bash
    cd /home/builder/twrp/
    source build/envsetup.sh
    BUILD_FLAVOR="userdebug"
    lunch omni_X70-${BUILD_FLAVOR}
    make -j$(nproc --all) recoveryimage'
    docker run -e CI=true nikitorex/prebuilt npm run test -- --coverage

after_success:
  - export version=$(grep "define TW_MAIN_VERSION_STR" bootable/recovery/variables.h | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/X70/prebuilt.img HOME/twrp/TWRP-{5.1}-X70-(date +"%Y%m%d")-Unofficial.img https://file.io && echo ""
  - curl -s --upload-file TWRP-{5.1}-X70-(date +"%Y%m%d")-Unofficial.img https://file.io && echo ""
  - cd $HOME/twrp/

deploy:
  cleanup: true
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - $HOME/twrp/*.img
    - $HOME/twrp/*.zip
  on:
    tags: true
    repo: NikitoRex/prebuilt
    branch: main


branches:
  only:
    - main

except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
